# PostgreSQL
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: rsfga-test
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: rsfga-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: rsfga
            - name: POSTGRES_PASSWORD
              value: rsfga
            - name: POSTGRES_DB
              value: rsfga
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "rsfga"]
            initialDelaySeconds: 5
            periodSeconds: 5

# CockroachDB
---
apiVersion: v1
kind: Service
metadata:
  name: cockroachdb
  namespace: rsfga-test
spec:
  ports:
    - port: 26257
      targetPort: 26257
  selector:
    app: cockroachdb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cockroachdb
  namespace: rsfga-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cockroachdb
  template:
    metadata:
      labels:
        app: cockroachdb
    spec:
      containers:
        - name: cockroachdb
          image: cockroachdb/cockroach:latest
          args: ["start-single-node", "--insecure"]
          ports:
            - containerPort: 26257
          readinessProbe:
            httpGet:
              path: /health?ready=1
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5

# MariaDB
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: rsfga-test
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mariadb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: rsfga-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:10.11
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: rsfga
            - name: MYSQL_DATABASE
              value: rsfga
            - name: MYSQL_USER
              value: rsfga
            - name: MYSQL_PASSWORD
              value: rsfga
          readinessProbe:
            exec:
              command: ["mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prsfga"]
            initialDelaySeconds: 10
            periodSeconds: 5

# TiDB
---
apiVersion: v1
kind: Service
metadata:
  name: tidb
  namespace: rsfga-test
spec:
  ports:
    - port: 4000
      targetPort: 4000
  selector:
    app: tidb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tidb
  namespace: rsfga-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tidb
  template:
    metadata:
      labels:
        app: tidb
    spec:
      containers:
        - name: tidb
          image: pingcap/tidb:latest
          ports:
            - containerPort: 4000
          readinessProbe:
            tcpSocket:
              port: 4000
            initialDelaySeconds: 10
            periodSeconds: 5
